baseURL = 'https://otabuzzman.com/'
languageCode = 'en-us'
title = "otabuzzman's blog"
# use beautiful ananke theme module
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

publishDir = "/opt/otabuzzman/www"

# use content module from hub
[module.imports]
  path = 'github.com/otabuzzman/otabuzzman.hub'
  disabled = false
  [[module.imports.mounts]]
    source = 'modules/content'
    target = 'content'
  [[module.imports.mounts]]
    source = 'modules/static'
    target = 'static'

[[params.ananke_socials]]
  name = "twitter"
  url = "https://twitter.com/otabuzzman"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/otabuzzman"
