baseURL = 'https://otabuzzman.com/'
languageCode = 'en-us'
title = "otabuzzman's blog"

# use the beautiful Ananke theme
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

# publish to Apache web server
publishDir = "/opt/otabuzzman/www"

[markup.goldmark.parser.attribute]
# enable markdown attributes
block = true

# use content from repository
[module.imports]
  path = 'github.com/otabuzzman/otabuzzman.com'
  disabled = false
  [[module.imports.mounts]]
    source = 'content'
    target = 'content'
    excludeFiles = ['posts/**/backup']
  [[module.imports.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports.mounts]]
    source = 'layouts'
    target = 'layouts'

# custom CSS files loaded by Ananke
[params]
custom_css = ["custom.css"]

# follow and share on social media
[params.ananke.social.follow]
  new_window_icon = true
  networks = ["github", "x-twitter", "linkedin"]
[params.ananke.social.share]
  sharetext = true
  networks = ["x-twitter", "linkedin"]

[params.ananke.social.github]
  username = "otabuzzman"
[params.ananke.social.x-twitter]
  username = "otabuzzman"
[params.ananke.social.linkedin]
  username = "juergenschuck"
